### ISSUE TITLE
Development environment.

### ISSUE THREAD

**Issue by AnakinFrontwalker** [Drakemor/WebChat#3]
- Access to chat on localhost, environment should be close to the server. (Later, when db will be chosen, db should also be able to be set on local)
- Possibility to log in with fake facebook authorization (mock user object).

**Comment by Drakemor** [comment]
Tommorow I plan to add server files to our repo - this will enable devs to run it locally, db issue is open.
Second question is another matter, why you think we need that as a separate feature, and how would it work? Facebook itself has this option to create dummy accounts: http://prntscr.com/c1anyr

**Comment by AnakinFrontwalker** [comment]
Automatic tests for example, if we want to add them later.
